//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgosProcessor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=INPAKRO39088;Initial Catalog=Animal_Movement;Integrated Security=True" +
            "")]
        public string Animal_MovementConnectionString {
            get {
                return ((string)(this["Animal_MovementConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Telonics\\Data Converter\\TDC.exe")]
        public string tdc_commandline {
            get {
                return ((string)(this["tdc_commandline"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<BatchSettings>\r\n  {0}\r\n  <ParameterFile>{1}</ParameterFile>\r\n  <OutputFolder>{2}" +
            "</OutputFolder>\r\n  <BatchLog>{3}</BatchLog>\r\n  <MoveFiles>false</MoveFiles>\r\n  <" +
            "GoogleEarth>false</GoogleEarth>\r\n</BatchSettings>")]
        public string tpf_batchfile_template {
            get {
                return ((string)(this["tpf_batchfile_template"]));
            }
            set {
                this["tpf_batchfile_template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<ArgosFile>{0}</ArgosFile>")]
        public string tpf_batchfile_argosline_template {
            get {
                return ((string)(this["tpf_batchfile_argosline_template"]));
            }
            set {
                this["tpf_batchfile_argosline_template"] = value;
            }
        }
    }
}
