//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalMovement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddFileFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["AddFileFormLocation"]));
            }
            set {
                this["AddFileFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddAnimalFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["AddAnimalFormLocation"]));
            }
            set {
                this["AddAnimalFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddCollarFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["AddCollarFormLocation"]));
            }
            set {
                this["AddCollarFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddEditorFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["AddEditorFormLocation"]));
            }
            set {
                this["AddEditorFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddProjectFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["AddProjectFormLocation"]));
            }
            set {
                this["AddProjectFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AnimalDetailsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["AnimalDetailsFormLocation"]));
            }
            set {
                this["AnimalDetailsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ChangeInvestigatorFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["ChangeInvestigatorFormLocation"]));
            }
            set {
                this["ChangeInvestigatorFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point CollarAnimalFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["CollarAnimalFormLocation"]));
            }
            set {
                this["CollarAnimalFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point CollarDetailsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["CollarDetailsFormLocation"]));
            }
            set {
                this["CollarDetailsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point CreateQueryLayerFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["CreateQueryLayerFormLocation"]));
            }
            set {
                this["CreateQueryLayerFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DeployCollarFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["DeployCollarFormLocation"]));
            }
            set {
                this["DeployCollarFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FileContentsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["FileContentsFormLocation"]));
            }
            set {
                this["FileContentsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FileDetailsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["FileDetailsFormLocation"]));
            }
            set {
                this["FileDetailsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point InvestigatorFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["InvestigatorFormLocation"]));
            }
            set {
                this["InvestigatorFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ProjectDetailsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["ProjectDetailsFormLocation"]));
            }
            set {
                this["ProjectDetailsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ProjectsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["ProjectsFormLocation"]));
            }
            set {
                this["ProjectsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RetrieveCollarFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["RetrieveCollarFormLocation"]));
            }
            set {
                this["RetrieveCollarFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("375, 320")]
        public global::System.Drawing.Size AddAnimalFormSize {
            get {
                return ((global::System.Drawing.Size)(this["AddAnimalFormSize"]));
            }
            set {
                this["AddAnimalFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("376, 370")]
        public global::System.Drawing.Size AddCollarFormSize {
            get {
                return ((global::System.Drawing.Size)(this["AddCollarFormSize"]));
            }
            set {
                this["AddCollarFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("405, 246")]
        public global::System.Drawing.Size AddEditorFormSize {
            get {
                return ((global::System.Drawing.Size)(this["AddEditorFormSize"]));
            }
            set {
                this["AddEditorFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("284, 260")]
        public global::System.Drawing.Size AddFileFormSize {
            get {
                return ((global::System.Drawing.Size)(this["AddFileFormSize"]));
            }
            set {
                this["AddFileFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("324, 220")]
        public global::System.Drawing.Size AddProjectFormSize {
            get {
                return ((global::System.Drawing.Size)(this["AddProjectFormSize"]));
            }
            set {
                this["AddProjectFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("465, 255")]
        public global::System.Drawing.Size AnimalDetailsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["AnimalDetailsFormSize"]));
            }
            set {
                this["AnimalDetailsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("330, 170")]
        public global::System.Drawing.Size ChangeInvestigatorFormSize {
            get {
                return ((global::System.Drawing.Size)(this["ChangeInvestigatorFormSize"]));
            }
            set {
                this["ChangeInvestigatorFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("290, 155")]
        public global::System.Drawing.Size CollarAnimalFormSize {
            get {
                return ((global::System.Drawing.Size)(this["CollarAnimalFormSize"]));
            }
            set {
                this["CollarAnimalFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 300")]
        public global::System.Drawing.Size CollarDetailsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["CollarDetailsFormSize"]));
            }
            set {
                this["CollarDetailsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("531, 419")]
        public global::System.Drawing.Size CreateQueryLayerFormSize {
            get {
                return ((global::System.Drawing.Size)(this["CreateQueryLayerFormSize"]));
            }
            set {
                this["CreateQueryLayerFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("290, 155")]
        public global::System.Drawing.Size DeployCollarFormSize {
            get {
                return ((global::System.Drawing.Size)(this["DeployCollarFormSize"]));
            }
            set {
                this["DeployCollarFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("427, 440")]
        public global::System.Drawing.Size FileContentsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["FileContentsFormSize"]));
            }
            set {
                this["FileContentsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("492, 331")]
        public global::System.Drawing.Size FileDetailsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["FileDetailsFormSize"]));
            }
            set {
                this["FileDetailsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("462, 434")]
        public global::System.Drawing.Size InvestigatorFormSize {
            get {
                return ((global::System.Drawing.Size)(this["InvestigatorFormSize"]));
            }
            set {
                this["InvestigatorFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("231, 194")]
        public global::System.Drawing.Size MainFormSize {
            get {
                return ((global::System.Drawing.Size)(this["MainFormSize"]));
            }
            set {
                this["MainFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("536, 406")]
        public global::System.Drawing.Size ProjectDetailsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["ProjectDetailsFormSize"]));
            }
            set {
                this["ProjectDetailsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("602, 251")]
        public global::System.Drawing.Size ProjectsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["ProjectsFormSize"]));
            }
            set {
                this["ProjectsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 102")]
        public global::System.Drawing.Size RetrieveCollarFormSize {
            get {
                return ((global::System.Drawing.Size)(this["RetrieveCollarFormSize"]));
            }
            set {
                this["RetrieveCollarFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("185")]
        public int CreateQueryLayerFormSplitter1Distance {
            get {
                return ((int)(this["CreateQueryLayerFormSplitter1Distance"]));
            }
            set {
                this["CreateQueryLayerFormSplitter1Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112")]
        public int CreateQueryLayerFormSplitter2Distance {
            get {
                return ((int)(this["CreateQueryLayerFormSplitter2Distance"]));
            }
            set {
                this["CreateQueryLayerFormSplitter2Distance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point CollarParameterFileDetailsFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["CollarParameterFileDetailsFormLocation"]));
            }
            set {
                this["CollarParameterFileDetailsFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("508, 300")]
        public global::System.Drawing.Size CollarParameterFileDetailsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["CollarParameterFileDetailsFormSize"]));
            }
            set {
                this["CollarParameterFileDetailsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddCollarParameterFileFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["AddCollarParameterFileFormLocation"]));
            }
            set {
                this["AddCollarParameterFileFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 166")]
        public global::System.Drawing.Size AddCollarParameterFileFormSize {
            get {
                return ((global::System.Drawing.Size)(this["AddCollarParameterFileFormSize"]));
            }
            set {
                this["AddCollarParameterFileFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddFolderFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["AddFolderFormLocation"]));
            }
            set {
                this["AddFolderFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("284, 317")]
        public global::System.Drawing.Size AddFolderFormSize {
            get {
                return ((global::System.Drawing.Size)(this["AddFolderFormSize"]));
            }
            set {
                this["AddFolderFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InvestigatorFormActiveTab {
            get {
                return ((int)(this["InvestigatorFormActiveTab"]));
            }
            set {
                this["InvestigatorFormActiveTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InvestigatorFormShowEmailFiles {
            get {
                return ((bool)(this["InvestigatorFormShowEmailFiles"]));
            }
            set {
                this["InvestigatorFormShowEmailFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InvestigatorFormShowDownloadFiles {
            get {
                return ((bool)(this["InvestigatorFormShowDownloadFiles"]));
            }
            set {
                this["InvestigatorFormShowDownloadFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InvestigatorFormShowDerivedFiles {
            get {
                return ((bool)(this["InvestigatorFormShowDerivedFiles"]));
            }
            set {
                this["InvestigatorFormShowDerivedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProjectDetailsFormActiveTab {
            get {
                return ((int)(this["ProjectDetailsFormActiveTab"]));
            }
            set {
                this["ProjectDetailsFormActiveTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProjectDetailsFormShowEmailFiles {
            get {
                return ((bool)(this["ProjectDetailsFormShowEmailFiles"]));
            }
            set {
                this["ProjectDetailsFormShowEmailFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProjectDetailsFormShowDownloadFiles {
            get {
                return ((bool)(this["ProjectDetailsFormShowDownloadFiles"]));
            }
            set {
                this["ProjectDetailsFormShowDownloadFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProjectDetailsFormShowDerivedFiles {
            get {
                return ((bool)(this["ProjectDetailsFormShowDerivedFiles"]));
            }
            set {
                this["ProjectDetailsFormShowDerivedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point UploadFilesFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["UploadFilesFormLocation"]));
            }
            set {
                this["UploadFilesFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("440, 364")]
        public global::System.Drawing.Size UploadFilesFormSize {
            get {
                return ((global::System.Drawing.Size)(this["UploadFilesFormSize"]));
            }
            set {
                this["UploadFilesFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CollarDetailsFormActiveTab {
            get {
                return ((int)(this["CollarDetailsFormActiveTab"]));
            }
            set {
                this["CollarDetailsFormActiveTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InvestigatorReports.xml")]
        public string InvestigatorReportsXml {
            get {
                return ((string)(this["InvestigatorReportsXml"]));
            }
            set {
                this["InvestigatorReportsXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AnimalDetailsFormActiveTab {
            get {
                return ((int)(this["AnimalDetailsFormActiveTab"]));
            }
            set {
                this["AnimalDetailsFormActiveTab"] = value;
            }
        }
    }
}
