USE [master]
GO

CREATE DATABASE [Animal_Movement] ON  PRIMARY 
( NAME = N'Animal_Movement', FILENAME = N'C:\SqlDB\SQL2008R2\Data\Animal_Movement.mdf' , SIZE = 113088KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Animal_Movement_log', FILENAME = N'C:\SqlDB\SQL2008R2\Log\Animal_Movement_log.ldf' , SIZE = 833024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Animal_Movement] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Animal_Movement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Animal_Movement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Animal_Movement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Animal_Movement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Animal_Movement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Animal_Movement] SET ARITHABORT OFF 
GO

ALTER DATABASE [Animal_Movement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Animal_Movement] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Animal_Movement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Animal_Movement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Animal_Movement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Animal_Movement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Animal_Movement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Animal_Movement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Animal_Movement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Animal_Movement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Animal_Movement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Animal_Movement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Animal_Movement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Animal_Movement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Animal_Movement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Animal_Movement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Animal_Movement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Animal_Movement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Animal_Movement] SET  READ_WRITE 
GO

ALTER DATABASE [Animal_Movement] SET RECOVERY FULL 
GO

ALTER DATABASE [Animal_Movement] SET  MULTI_USER 
GO

ALTER DATABASE [Animal_Movement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Animal_Movement] SET DB_CHAINING OFF 
GO

USE [Animal_Movement]
GO

GRANT ALTER ANY USER TO [Investigator] AS [dbo]
GO

GRANT CONNECT TO [NPS\Domain Users] AS [dbo]
GO

