USE [master]
GO

CREATE DATABASE [Animal_Movement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Animal_Movement', FILENAME = N'E:\SQLSDE\MSSQL\DATA\AM\Animal_Movement.mdf' , SIZE = 7386624KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Animal_Movement_log', FILENAME = N'E:\SQLSDE\MSSQL\LOG\Animal_Movement_log.ldf' , SIZE = 9703232KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Animal_Movement] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Animal_Movement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Animal_Movement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Animal_Movement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Animal_Movement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Animal_Movement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Animal_Movement] SET ARITHABORT OFF 
GO

ALTER DATABASE [Animal_Movement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Animal_Movement] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Animal_Movement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Animal_Movement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Animal_Movement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Animal_Movement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Animal_Movement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Animal_Movement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Animal_Movement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Animal_Movement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Animal_Movement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Animal_Movement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Animal_Movement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Animal_Movement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Animal_Movement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Animal_Movement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Animal_Movement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Animal_Movement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Animal_Movement] SET RECOVERY FULL 
GO

ALTER DATABASE [Animal_Movement] SET  MULTI_USER 
GO

ALTER DATABASE [Animal_Movement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Animal_Movement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Animal_Movement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Animal_Movement] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

USE [Animal_Movement]
GO

CREATE USER [INPAKROVMAIS\sql_proxy] FOR LOGIN [INPAKROVMAIS\sql_proxy] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\abaltensperger] FOR LOGIN [NPS\abaltensperger] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\BAMangipane] FOR LOGIN [NPS\BAMangipane] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\BBorg] FOR LOGIN [NPS\BBorg] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\Domain Users] FOR LOGIN [NPS\Domain Users]
GO

CREATE USER [NPS\JAPutera] FOR LOGIN [NPS\JAPutera] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\JPLawler] FOR LOGIN [NPS\JPLawler] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\JSShearer] FOR LOGIN [NPS\JSShearer] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\JWBurch] FOR LOGIN [NPS\JWBurch] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\KCJoly] FOR LOGIN [NPS\KCJoly] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\mdcameron] FOR LOGIN [NPS\mdcameron] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\MLJohnson] FOR LOGIN [NPS\MLJohnson] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\msorum] FOR LOGIN [NPS\msorum] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\PAOwen] FOR LOGIN [NPS\PAOwen] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\RESarwas] FOR LOGIN [NPS\RESarwas] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\SArthur] FOR LOGIN [NPS\SArthur] WITH DEFAULT_SCHEMA=[dbo]
GO

CREATE USER [NPS\SDMiller] FOR LOGIN [NPS\SDMiller] WITH DEFAULT_SCHEMA=[dbo]
GO

GRANT CONNECT TO [INPAKROMS53AIS\repl_distribution] AS [dbo]
GO

GRANT CONNECT REPLICATION TO [INPAKROMS53AIS\repl_distribution] AS [dbo]
GO

GRANT CONNECT TO [INPAKROMS53AIS\repl_logreader] AS [dbo]
GO

GRANT CONNECT TO [INPAKROMS53AIS\repl_merge] AS [dbo]
GO

GRANT CONNECT TO [INPAKROMS53AIS\repl_snapshot] AS [dbo]
GO

GRANT CONNECT TO [INPAKROVMAIS\sql_proxy] AS [dbo]
GO

GRANT ALTER ANY USER TO [Investigator] AS [dbo]
GO

GRANT CONNECT TO [NPS\abaltensperger] AS [dbo]
GO

GRANT CONNECT TO [NPS\BBorg] AS [dbo]
GO

GRANT CONNECT TO [NPS\Domain Users] AS [dbo]
GO

GRANT CONNECT TO [NPS\GVHilderbrand] AS [dbo]
GO

GRANT CONNECT TO [NPS\JAPutera] AS [dbo]
GO

GRANT CONNECT TO [NPS\JPLawler] AS [dbo]
GO

GRANT CONNECT TO [NPS\JSShearer] AS [dbo]
GO

GRANT CONNECT TO [NPS\mdcameron] AS [dbo]
GO

GRANT CONNECT TO [NPS\MLJohnson] AS [dbo]
GO

GRANT CONNECT TO [NPS\msorum] AS [dbo]
GO

GRANT CONNECT TO [NPS\PAOwen] AS [dbo]
GO

GRANT CONNECT TO [NPS\RESarwas] AS [dbo]
GO

GRANT CONNECT TO [NPS\SArthur] AS [dbo]
GO

ALTER DATABASE [Animal_Movement] SET  READ_WRITE 
GO

