USE [Animal_Movement]
GO
INSERT [dbo].[LookupCollarModels] ([CollarModel]) VALUES (N'TelonicsGen3')
INSERT [dbo].[LookupCollarModels] ([CollarModel]) VALUES (N'TelonicsGen3_PTT')
INSERT [dbo].[LookupCollarModels] ([CollarModel]) VALUES (N'TelonicsGen3_VHF')
INSERT [dbo].[LookupCollarModels] ([CollarModel]) VALUES (N'TelonicsGen4')
INSERT [dbo].[LookupCollarModels] ([CollarModel]) VALUES (N'TelonicsGen4_PTT')
INSERT [dbo].[LookupCollarModels] ([CollarModel]) VALUES (N'TelonicsGen4_VHF')
INSERT [dbo].[LookupCollarModels] ([CollarModel]) VALUES (N'Unknown')
INSERT [dbo].[LookupCollarManufacturers] ([CollarManufacturer], [Name], [Website], [Description]) VALUES (N'Televilt', N'Tellus GPS systems', N'http://wildlife.followit.se', N'Followit AB, Bandygatan 2, 711 34 Lindesberg; Tel: +46 (0)581-171 90; Fax: +46 (0)581-171 96; E-mail: wildlifesales@followit.se')
INSERT [dbo].[LookupCollarManufacturers] ([CollarManufacturer], [Name], [Website], [Description]) VALUES (N'Telonics', N'Telonics, Inc.', N'http://www.telonics.com', N'932 E. Impala Avenue Mesa, AZ, 85204-6699 USA Tel: 480-892-4444 FAX: 480-892-9139')
INSERT [dbo].[LookupCollarFileStatus] ([Code], [Name], [Description]) VALUES (N'A', N'Active', N'File is archived in the database and used to create movement vectors')
INSERT [dbo].[LookupCollarFileStatus] ([Code], [Name], [Description]) VALUES (N'I', N'Inactive', N'File is archived in the database, but not used in calculating movement vectors')
INSERT [dbo].[LookupSpecies] ([Species]) VALUES (N'Bear')
INSERT [dbo].[LookupSpecies] ([Species]) VALUES (N'Caribou')
INSERT [dbo].[LookupSpecies] ([Species]) VALUES (N'Moose')
INSERT [dbo].[LookupSpecies] ([Species]) VALUES (N'Muskox')
INSERT [dbo].[LookupSpecies] ([Species]) VALUES (N'Sheep')
INSERT [dbo].[LookupSpecies] ([Species]) VALUES (N'Wolf')
INSERT [dbo].[LookupQueryLayerServers] ([Location], [Connection], [Database]) VALUES (N'AKRO', N'INPAKROMS53AIS', N'Animal_Movement')
INSERT [dbo].[LookupQueryLayerServers] ([Location], [Connection], [Database]) VALUES (N'Regan''s Laptop', N'INPAKRO39306', N'AnimalMovementRepl')
INSERT [dbo].[LookupGender] ([Sex]) VALUES (N'Female')
INSERT [dbo].[LookupGender] ([Sex]) VALUES (N'Male')
INSERT [dbo].[LookupGender] ([Sex]) VALUES (N'Unknown')
INSERT [dbo].[LookupCollarFileFormats] ([Code], [CollarManufacturer], [Name], [Description], [TableName], [HasCollarIdColumn]) VALUES (N'A', N'Telonics', N'Telonics Gen3 Store On Board', N'This is the output file from the Telonic Data Download Utility software for Gen3 collar download.', N'CollarDataTelonicsStoreOnBoard', N'N')
INSERT [dbo].[LookupCollarFileFormats] ([Code], [CollarManufacturer], [Name], [Description], [TableName], [HasCollarIdColumn]) VALUES (N'B', N'Telonics', N'Ed Debevek''s File Format', N'This is the csv version of the output from Ed Debevek''s website', N'CollarDataDebevekFormat', N'Y')
INSERT [dbo].[LookupCollarFileFormats] ([Code], [CollarManufacturer], [Name], [Description], [TableName], [HasCollarIdColumn]) VALUES (N'C', N'Telonics', N'Telonics Gen4 Output', N'This is the output file from TDC software - either condensed or complete, and transmitted either by Argos or by collar download', N'CollarDataTelonicsGen4', N'N')
INSERT [dbo].[LookupCollarFileFormats] ([Code], [CollarManufacturer], [Name], [Description], [TableName], [HasCollarIdColumn]) VALUES (N'D', N'Telonics', N'Telonics Gen3 Output', N'This is the output file from the ADC-T03 software for GPS data transmitted by Argos.', N'CollarDataTelonicsGen3', N'N')
INSERT [dbo].[LookupCollarFileFormats] ([Code], [CollarManufacturer], [Name], [Description], [TableName], [HasCollarIdColumn]) VALUES (N'E', N'Telonics', N'Telonics/Argos Email', N'Data from the Argos Email or website system', N'varies', N'Y')
INSERT [dbo].[LookupCollarFileFormats] ([Code], [CollarManufacturer], [Name], [Description], [TableName], [HasCollarIdColumn]) VALUES (N'F', N'Telonics', N'Telonics/Argos Website-download', N'Data from the Argos Email or website system', N'varies', N'Y')
INSERT [dbo].[LookupCollarFileFormats] ([Code], [CollarManufacturer], [Name], [Description], [TableName], [HasCollarIdColumn]) VALUES (N'G', N'Telonics', N'Telonics/Argos Email Organizer', N'This is a psuedo file format, it is used for collecting all emails under one umbrela format', N'varies', N'Y')
INSERT [dbo].[LookupCollarFileFormats] ([Code], [CollarManufacturer], [Name], [Description], [TableName], [HasCollarIdColumn]) VALUES (N'H', N'Telonics', N'Telonics/Argos Website-download Organizer', N'This is a psuedo file format, it is used for collecting all emails under one umbrela format', N'varies', N'Y')
INSERT [dbo].[LookupCollarParameterFileFormats] ([Code], [CollarManufacturer], [Name], [Description]) VALUES (N'A', N'Telonics', N'TPF', N'Telonics Parameter File (*.tpf) for Gen4 GPS/Argos Collars')
INSERT [dbo].[LookupCollarParameterFileFormats] ([Code], [CollarManufacturer], [Name], [Description]) VALUES (N'B', N'Telonics', N'PPF', N'Telonics PTT Properties File (*.ppf) - for Gen3 GPS/Argos Collars')
INSERT [dbo].[LookupCollarFileHeaders] ([Header], [FileFormat]) VALUES (N'CollarID,', N'B')
INSERT [dbo].[LookupCollarFileHeaders] ([Header], [FileFormat]) VALUES (N'Fix #	Date	Time	Fix Status	Status Text	Velocity East(m/s)	Velocity North(m/s)	Velocity Up(m/s)	Latitude	Longitude	Altitude(m)	PDOP	HDOP	VDOP	TDOP	Temperature Sensor(deg.)	Activity Sensor	Satellite Data', N'A')
INSERT [dbo].[LookupCollarFileHeaders] ([Header], [FileFormat]) VALUES (N'Fix #,Date,Time,Fix Status,Status Text,Velocity East(m/s),Velocity North(m/s),Velocity Up(m/s),Latitude,Longitude,Altitude(m),PDOP,HDOP,VDOP,TDOP,Temperature Sensor(deg.),Activity Sensor,Satellite Data,', N'A')
INSERT [dbo].[LookupCollarFileHeaders] ([Header], [FileFormat]) VALUES (N'Telonics Data Report', N'C')
INSERT [dbo].[LookupCollarFileHeaders] ([Header], [FileFormat]) VALUES (N'TXDate,TXTime,PTTID,FixNum,FixQual,FixDate,FixTime,Longitude,Latitude', N'D')
