<?xml version="1.0" encoding="utf-8"?><Database Name="Animal_Movement" Class="AnimalMovementViews" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=INPAKROMS53AIS;Initial Catalog=Animal_Movement;Integrated Security=True" SettingsObjectName="DataModel.Properties.Settings" SettingsPropertyName="Animal_MovementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AnimalFixesByFile" Member="AnimalFixesByFiles">
    <Type Name="AnimalFixesByFile">
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CollarId" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Project" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="AnimalId" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="[First Fix]" Member="First_Fix" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="[Last Fix]" Member="Last_Fix" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="[Number of Fixes]" Member="Number_of_Fixes" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ArgosFile_NeedsPartialProcessing" Member="PartiallyProcessedArgosFiles">
    <Type Name="PartiallyProcessedArgosFiles">
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlatformId" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ArgosFile_NeverProcessed" Member="NeverProcessedArgosFiles">
    <Type Name="NeverProcessedArgosFiles">
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DataLog_NeverProcessed" Member="NeverProcessedDataLogFiles">
    <Type Name="NeverProcessedDataLogFiles">
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.AnimalLocationSummary" Method="AnimalLocationSummary" IsComposable="true">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="AnimalId" Parameter="animalId" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="AnimalLocationSummaryResult">
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Left]" Member="Left" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Right]" Member="Right" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Bottom" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Top]" Member="Top" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="First" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Last" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CollarFixesByFile" Method="CollarFixesByFile" IsComposable="true">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="CollarFixesByFileResult">
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[File]" Member="File" Type="System.String" DbType="NVarChar(259) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="FixCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="First" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Last" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CollarFixSummary" Method="CollarFixSummary" IsComposable="true">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="CollarFixSummaryResult">
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Unique]" Member="Unique" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="First" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Last" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConflictingFixes" Method="ConflictingFixes" IsComposable="true">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="LastXdays" Parameter="lastXdays" Type="System.Int32" DbType="Int" />
    <ElementType Name="ConflictingFixesResult">
      <Column Name="FixId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HiddenBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LineNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocalFixTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Lat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Lon" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.DaysSinceLastDownload" Method="DaysSinceLastDownload" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FileHasGen4Data" Method="FileHasGen4Data" IsComposable="true">
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.GetTelonicsParametersForArgosDates" Method="GetTelonicsParametersForArgosDates" IsComposable="true">
    <Parameter Name="PlatformID" Parameter="platformID" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime2" />
    <ElementType Name="GetTelonicsParametersForArgosDatesResult">
      <Column Name="DeploymentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlatformId" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="CollarId" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="CollarModel" Type="System.String" DbType="VarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="Gen3Period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Format" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Contents" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>