<?xml version="1.0" encoding="utf-8"?><Database Name="Animal_Movement" Class="AnimalMovementFunctions" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=INPAKROVMAIS;Initial Catalog=Animal_Movement;Integrated Security=True" SettingsObjectName="DataModel.Properties.Settings" SettingsPropertyName="Animal_MovementConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.IsFixEditor" Method="IsFixEditor" IsComposable="true">
    <Parameter Name="FixId" Parameter="fixId" Type="System.Int32" DbType="Int" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.NextAnimalId" Method="NextAnimalId" IsComposable="true">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="VarChar(32)" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.ArgosFile_Process" Method="ArgosFile_Process">
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ArgosFile_ProcessPlatform" Method="ArgosFile_ProcessPlatform">
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PlatformId" Parameter="platformId" Type="System.String" DbType="VarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ArgosFile_UnProcessPlatform" Method="ArgosFile_UnProcessPlatform">
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PlatformId" Parameter="platformId" Type="System.String" DbType="VarChar(255)" />
    <ElementType Name="ArgosFile_UnProcessPlatformResult">
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ArgosFile_ClearProcessingResults" Method="ArgosFile_ClearProcessingResults">
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.IsProjectEditor" Method="IsProjectEditor" IsComposable="true">
    <Parameter Name="Project" Parameter="project" Type="System.String" DbType="VarChar(32)" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.IsInvestigatorEditor" Method="IsInvestigatorEditor" IsComposable="true">
    <Parameter Name="ProjectInvestigator" Parameter="projectInvestigator" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.CollarFile_FixOwnerOfIdfFile" Method="CollarFile_FixOwnerOfIdfFile">
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>