<?xml version="1.0" encoding="utf-8"?><Database Name="Animal_Movement" Class="AnimalMovementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=INPAKROVMAIS;Initial Catalog=Animal_Movement;Integrated Security=True" SettingsObjectName="DataModel.Properties.Settings" SettingsPropertyName="Animal_MovementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Animals" Member="Animals">
    <Type Name="Animal">
      <Column Name="ProjectId" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AnimalId" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Species" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="varchar(7)" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="MortalityDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="Animal_CollarDeployment" Member="CollarDeployments" ThisKey="ProjectId,AnimalId" OtherKey="ProjectId,AnimalId" Type="CollarDeployment" />
      <Association Name="Project_Animal" Member="Project" ThisKey="ProjectId" OtherKey="ProjectId" Type="Project" IsForeignKey="true" />
      <Association Name="LookupGender_Animal" Member="LookupGender" ThisKey="Gender" OtherKey="Sex" Type="LookupGender" IsForeignKey="true" />
      <Association Name="LookupSpecies_Animal" Member="LookupSpecies" ThisKey="Species" OtherKey="Species" Type="LookupSpecies" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId1">
      <Argument Parameter="projectId" Member="ProjectId" />
      <Argument Parameter="animalId" Member="AnimalId" />
      <Argument Parameter="species" Member="Species" />
      <Argument Parameter="gender" Member="Gender" />
      <Argument Parameter="mortalityDate" Member="MortalityDate" />
      <Argument Parameter="groupName" Member="GroupName" />
      <Argument Parameter="description" Member="Description" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId2">
      <Argument Parameter="projectId" Member="ProjectId" Version="Original" />
      <Argument Parameter="animalId" Member="AnimalId" Version="Original" />
      <Argument Parameter="species" Member="Species" />
      <Argument Parameter="gender" Member="Gender" />
      <Argument Parameter="mortalityDate" Member="MortalityDate" />
      <Argument Parameter="groupName" Member="GroupName" />
      <Argument Parameter="description" Member="Description" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId3">
      <Argument Parameter="projectId" Member="ProjectId" Version="Original" />
      <Argument Parameter="animalId" Member="AnimalId" Version="Original" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Project">
      <Column Name="ProjectId" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectInvestigator" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UnitCode" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Association Name="Project_Animal" Member="Animals" ThisKey="ProjectId" OtherKey="ProjectId" Type="Animal" />
      <Association Name="Project_ProjectEditor" Member="ProjectEditors" ThisKey="ProjectId" OtherKey="ProjectId" Type="ProjectEditor" />
      <Association Name="Project_CollarFile" Member="CollarFiles" ThisKey="ProjectId" OtherKey="ProjectId" Type="CollarFile" />
      <Association Name="ProjectInvestigator_Project" Member="ProjectInvestigator1" ThisKey="ProjectInvestigator" OtherKey="Login" Type="ProjectInvestigator" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId4">
      <Argument Parameter="projectId" Member="ProjectId" />
      <Argument Parameter="projectName" Member="ProjectName" />
      <Argument Parameter="projectInvestigator" Member="ProjectInvestigator" />
      <Argument Parameter="unitCode" Member="UnitCode" />
      <Argument Parameter="description" Member="Description" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId5">
      <Argument Parameter="projectId" Member="ProjectId" Version="Original" />
      <Argument Parameter="projectName" Member="ProjectName" />
      <Argument Parameter="unitCode" Member="UnitCode" />
      <Argument Parameter="projectInvestigator" Member="ProjectInvestigator" />
      <Argument Parameter="description" Member="Description" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId6">
      <Argument Parameter="projectId" Member="ProjectId" Version="Original" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.LookupCollarManufacturers" Member="LookupCollarManufacturers">
    <Type Name="LookupCollarManufacturer">
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Association Name="LookupCollarManufacturer_LookupCollarParameterFileFormat" Member="LookupCollarParameterFileFormats" ThisKey="CollarManufacturer" OtherKey="CollarManufacturer" Type="LookupCollarParameterFileFormat" />
      <Association Name="LookupCollarManufacturer_LookupCollarModel" Member="LookupCollarModels" ThisKey="CollarManufacturer" OtherKey="CollarManufacturer" Type="LookupCollarModel" />
      <Association Name="LookupCollarManufacturer_LookupCollarFileFormat" Member="LookupCollarFileFormats" ThisKey="CollarManufacturer" OtherKey="CollarManufacturer" Type="LookupCollarFileFormat" />
      <Association Name="LookupCollarManufacturer_Collar" Member="Collars" ThisKey="CollarManufacturer" OtherKey="CollarManufacturer" Type="Collar" />
      <Association Name="LookupCollarManufacturer_LookupCollarSensor" Member="LookupCollarSensors" ThisKey="CollarManufacturer" OtherKey="CollarManufacturer" Type="LookupCollarSensor" />
    </Type>
  </Table>
  <Table Name="dbo.LookupGender" Member="LookupGenders">
    <Type Name="LookupGender">
      <Column Name="Sex" Type="System.String" DbType="varchar(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="LookupGender_Animal" Member="Animals" ThisKey="Sex" OtherKey="Gender" Type="Animal" />
    </Type>
  </Table>
  <Table Name="dbo.LookupSpecies" Member="LookupSpecies">
    <Type Name="LookupSpecies">
      <Column Name="Species" Type="System.String" DbType="VarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="LookupSpecies_Animal" Member="Animals" ThisKey="Species" OtherKey="Species" Type="Animal" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectEditors" Member="ProjectEditors">
    <Type Name="ProjectEditor">
      <Column Name="ProjectId" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Editor" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Project_ProjectEditor" Member="Project" ThisKey="ProjectId" OtherKey="ProjectId" Type="Project" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId7">
      <Argument Parameter="projectId" Member="ProjectId" />
      <Argument Parameter="editor" Member="Editor" />
    </InsertFunction>
    <DeleteFunction FunctionId="FunctionId8">
      <Argument Parameter="projectId" Member="ProjectId" />
      <Argument Parameter="editor" Member="Editor" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.ProjectInvestigators" Member="ProjectInvestigators">
    <Type Name="ProjectInvestigator">
      <Column Name="Login" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="ProjectInvestigator_Project" Member="Projects" ThisKey="Login" OtherKey="ProjectInvestigator" Type="Project" />
      <Association Name="ProjectInvestigator_CollarParameterFile" Member="CollarParameterFiles" ThisKey="Login" OtherKey="Owner" Type="CollarParameterFile" />
      <Association Name="ProjectInvestigator_ArgosProgram" Member="ArgosPrograms" ThisKey="Login" OtherKey="Manager" Type="ArgosProgram" />
      <Association Name="ProjectInvestigator_CollarFile" Member="CollarFiles" ThisKey="Login" OtherKey="Owner" Type="CollarFile" />
      <Association Name="ProjectInvestigator_Collar" Member="Collars" ThisKey="Login" OtherKey="Manager" Type="Collar" />
      <Association Name="ProjectInvestigator_ProjectInvestigatorAssistant" Member="ProjectInvestigatorAssistants" ThisKey="Login" OtherKey="ProjectInvestigator" Type="ProjectInvestigatorAssistant" />
    </Type>
    <UpdateFunction FunctionId="FunctionId9">
      <Argument Parameter="login" Member="Login" Version="Original" />
      <Argument Parameter="name" Member="Name" />
      <Argument Parameter="email" Member="Email" />
      <Argument Parameter="phone" Member="Phone" />
    </UpdateFunction>
  </Table>
  <Table Name="dbo.CollarFixes" Member="CollarFixes">
    <Type Name="CollarFix">
      <Column Name="FixId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HiddenBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LineNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="CollarId" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="FixDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Lat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Lon" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="CollarFile_CollarFix" Member="CollarFile" ThisKey="FileId" OtherKey="FileId" Type="CollarFile" IsForeignKey="true" />
      <Association Name="Collar_CollarFix" Member="Collar" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="Collar" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LookupCollarParameterFileFormats" Member="LookupCollarParameterFileFormats">
    <Type Name="LookupCollarParameterFileFormat">
      <Column Name="Code" Type="System.Char" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LookupCollarParameterFileFormat_CollarParameterFile" Member="CollarParameterFiles" ThisKey="Code" OtherKey="Format" Type="CollarParameterFile" />
      <Association Name="LookupCollarManufacturer_LookupCollarParameterFileFormat" Member="LookupCollarManufacturer" ThisKey="CollarManufacturer" OtherKey="CollarManufacturer" Type="LookupCollarManufacturer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CollarDeployments" Member="CollarDeployments">
    <Type Name="CollarDeployment">
      <Column Name="DeploymentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="AnimalId" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="CollarId" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="DeploymentDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="RetrievalDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="Animal_CollarDeployment" Member="Animal" ThisKey="ProjectId,AnimalId" OtherKey="ProjectId,AnimalId" Type="Animal" IsForeignKey="true" />
      <Association Name="Collar_CollarDeployment" Member="Collar" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="Collar" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId10">
      <Argument Parameter="projectId" Member="ProjectId" />
      <Argument Parameter="animalId" Member="AnimalId" />
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="deploymentDate" Member="DeploymentDate" />
      <Argument Parameter="retrievalDate" Member="RetrievalDate" />
      <Argument Parameter="deploymentId" Member="DeploymentId" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId11">
      <Argument Parameter="deploymentId" Member="DeploymentId" Version="Original" />
      <Argument Parameter="projectId" Member="ProjectId" />
      <Argument Parameter="animalId" Member="AnimalId" />
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="deploymentDate" Member="DeploymentDate" />
      <Argument Parameter="retrievalDate" Member="RetrievalDate" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId12">
      <Argument Parameter="deploymentId" Member="DeploymentId" Version="Original" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.LookupCollarModels" Member="LookupCollarModels">
    <Type Name="LookupCollarModel">
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CollarModel" Type="System.String" DbType="VarChar(24) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="LookupCollarModel_Collar" Member="Collars" ThisKey="CollarManufacturer,CollarModel" OtherKey="CollarManufacturer,CollarModel" Type="Collar" />
      <Association Name="LookupCollarManufacturer_LookupCollarModel" Member="LookupCollarManufacturer" ThisKey="CollarManufacturer" OtherKey="CollarManufacturer" Type="LookupCollarManufacturer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CollarParameterFiles" Member="CollarParameterFiles">
    <Type Name="CollarParameterFile">
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Format" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="UploadDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="UploadUser" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Contents" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" IsDelayLoaded="true" />
      <Column Name="Status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Sha1Hash" Type="System.Data.Linq.Binary" DbType="VarBinary(8000)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="CollarParameterFile_CollarParameter" Member="CollarParameters" ThisKey="FileId" OtherKey="FileId" Type="CollarParameter" />
      <Association Name="LookupCollarParameterFileFormat_CollarParameterFile" Member="LookupCollarParameterFileFormat" ThisKey="Format" OtherKey="Code" Type="LookupCollarParameterFileFormat" IsForeignKey="true" />
      <Association Name="ProjectInvestigator_CollarParameterFile" Member="ProjectInvestigator" ThisKey="Owner" OtherKey="Login" Type="ProjectInvestigator" IsForeignKey="true" />
      <Association Name="LookupFileStatus_CollarParameterFile" Member="LookupFileStatus" ThisKey="Status" OtherKey="Code" Type="LookupFileStatus" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId13">
      <Argument Parameter="owner" Member="Owner" />
      <Argument Parameter="fileName" Member="FileName" />
      <Argument Parameter="format" Member="Format" />
      <Argument Parameter="contents" Member="Contents" />
      <Argument Parameter="status" Member="Status" />
      <Argument Parameter="fileId" Member="FileId" />
      <Argument Parameter="uploadDate" Member="UploadDate" />
      <Argument Parameter="uploadUser" Member="UploadUser" />
      <Argument Parameter="sha1Hash" Member="Sha1Hash" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId14">
      <Argument Parameter="fileId" Member="FileId" Version="Original" />
      <Argument Parameter="owner" Member="Owner" />
      <Argument Parameter="fileName" Member="FileName" />
      <Argument Parameter="format" Member="Format" />
      <Argument Parameter="status" Member="Status" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId15">
      <Argument Parameter="fileId" Member="FileId" Version="Original" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.LookupFileStatus" Member="LookupFileStatus">
    <Type Name="LookupFileStatus">
      <Column Name="Code" Type="System.Char" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LookupFileStatus_CollarParameterFile" Member="CollarParameterFiles" ThisKey="Code" OtherKey="Status" Type="CollarParameterFile" />
      <Association Name="LookupFileStatus_CollarFile" Member="CollarFiles" ThisKey="Code" OtherKey="Status" Type="CollarFile" />
    </Type>
  </Table>
  <Table Name="dbo.ArgosDownloads" Member="ArgosDownloads">
    <Type Name="ArgosDownload">
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime2 NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProgramId" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PlatformId" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Days" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="CollarFile_ArgosDownload" Member="CollarFile" ThisKey="FileId" OtherKey="FileId" Type="CollarFile" IsForeignKey="true" />
      <Association Name="ArgosPlatform_ArgosDownload" Member="ArgosPlatform" ThisKey="PlatformId" OtherKey="PlatformId" Type="ArgosPlatform" IsForeignKey="true" />
      <Association Name="ArgosProgram_ArgosDownload" Member="ArgosProgram" ThisKey="ProgramId" OtherKey="ProgramId" Type="ArgosProgram" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId16">
      <Argument Parameter="programId" Member="ProgramId" />
      <Argument Parameter="platformId" Member="PlatformId" />
      <Argument Parameter="days" Member="Days" />
      <Argument Parameter="fileId" Member="FileId" />
      <Argument Parameter="errorMessage" Member="ErrorMessage" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.ArgosPlatforms" Member="ArgosPlatforms">
    <Type Name="ArgosPlatform">
      <Column Name="PlatformId" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProgramId" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisposalDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="ArgosPlatform_ArgosDownload" Member="ArgosDownloads" ThisKey="PlatformId" OtherKey="PlatformId" Type="ArgosDownload" />
      <Association Name="ArgosPlatform_ArgosDeployment" Member="ArgosDeployments" ThisKey="PlatformId" OtherKey="PlatformId" Type="ArgosDeployment" />
      <Association Name="ArgosPlatform_ArgosFileProcessingIssue" Member="ArgosFileProcessingIssues" ThisKey="PlatformId" OtherKey="PlatformId" Type="ArgosFileProcessingIssue" />
      <Association Name="ArgosPlatform_ArgosFilePlatformDate" Member="ArgosFilePlatformDates" ThisKey="PlatformId" OtherKey="PlatformId" Type="ArgosFilePlatformDate" />
      <Association Name="ArgosProgram_ArgosPlatform" Member="ArgosProgram" ThisKey="ProgramId" OtherKey="ProgramId" Type="ArgosProgram" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId17">
      <Argument Parameter="platformId" Member="PlatformId" />
      <Argument Parameter="programId" Member="ProgramId" />
      <Argument Parameter="disposalDate" Member="DisposalDate" />
      <Argument Parameter="notes" Member="Notes" />
      <Argument Parameter="active" Member="Active" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId18">
      <Argument Parameter="oldPlatformId" Member="PlatformId" Version="Original" />
      <Argument Parameter="newPlatformId" Member="PlatformId" />
      <Argument Parameter="programId" Member="ProgramId" />
      <Argument Parameter="disposalDate" Member="DisposalDate" />
      <Argument Parameter="notes" Member="Notes" />
      <Argument Parameter="active" Member="Active" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId19">
      <Argument Parameter="platformId" Member="PlatformId" Version="Original" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.ArgosPrograms" Member="ArgosPrograms">
    <Type Name="ArgosProgram">
      <Column Name="ProgramId" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProgramName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Manager" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ArgosProgram_ArgosDownload" Member="ArgosDownloads" ThisKey="ProgramId" OtherKey="ProgramId" Type="ArgosDownload" />
      <Association Name="ArgosProgram_ArgosPlatform" Member="ArgosPlatforms" ThisKey="ProgramId" OtherKey="ProgramId" Type="ArgosPlatform" />
      <Association Name="ProjectInvestigator_ArgosProgram" Member="ProjectInvestigator" ThisKey="Manager" OtherKey="Login" Type="ProjectInvestigator" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId20">
      <Argument Parameter="programId" Member="ProgramId" />
      <Argument Parameter="programName" Member="ProgramName" />
      <Argument Parameter="userName" Member="UserName" />
      <Argument Parameter="password" Member="Password" />
      <Argument Parameter="manager" Member="Manager" />
      <Argument Parameter="startDate" Member="StartDate" />
      <Argument Parameter="endDate" Member="EndDate" />
      <Argument Parameter="notes" Member="Notes" />
      <Argument Parameter="active" Member="Active" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId21">
      <Argument Parameter="oldProgramId" Member="ProgramId" Version="Original" />
      <Argument Parameter="newProgramId" Member="ProgramId" />
      <Argument Parameter="programName" Member="ProgramName" />
      <Argument Parameter="userName" Member="UserName" />
      <Argument Parameter="password" Member="Password" />
      <Argument Parameter="manager" Member="Manager" />
      <Argument Parameter="startDate" Member="StartDate" />
      <Argument Parameter="endDate" Member="EndDate" />
      <Argument Parameter="notes" Member="Notes" />
      <Argument Parameter="active" Member="Active" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId22">
      <Argument Parameter="programId" Member="ProgramId" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.LookupCollarFileFormats" Member="LookupCollarFileFormats">
    <Type Name="LookupCollarFileFormat">
      <Column Name="Code" Type="System.Char" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ArgosData" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="RequiresCollar" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="LookupCollarFileFormat_CollarFile" Member="CollarFiles" ThisKey="Code" OtherKey="Format" Type="CollarFile" />
      <Association Name="LookupCollarManufacturer_LookupCollarFileFormat" Member="LookupCollarManufacturer" ThisKey="CollarManufacturer" OtherKey="CollarManufacturer" Type="LookupCollarManufacturer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CollarParameters" Member="CollarParameters">
    <Type Name="CollarParameter">
      <Column Name="ParameterId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="CollarId" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="FileId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gen3Period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="CollarParameter_CollarFile" Member="CollarFiles" ThisKey="ParameterId" OtherKey="CollarParameterId" Type="CollarFile" />
      <Association Name="CollarParameterFile_CollarParameter" Member="CollarParameterFile" ThisKey="FileId" OtherKey="FileId" Type="CollarParameterFile" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Collar_CollarParameter" Member="Collar" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="Collar" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId23">
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="fileId" Member="FileId" />
      <Argument Parameter="gen3Period" Member="Gen3Period" />
      <Argument Parameter="startDate" Member="StartDate" />
      <Argument Parameter="endDate" Member="EndDate" />
      <Argument Parameter="parameterId" Member="ParameterId" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId24">
      <Argument Parameter="parameterId" Member="ParameterId" Version="Original" />
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="fileId" Member="FileId" />
      <Argument Parameter="gen3Period" Member="Gen3Period" />
      <Argument Parameter="startDate" Member="StartDate" />
      <Argument Parameter="endDate" Member="EndDate" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId25">
      <Argument Parameter="parameterId" Member="ParameterId" Version="Original" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.ArgosDeployments" Member="ArgosDeployments">
    <Type Name="ArgosDeployment">
      <Column Name="DeploymentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlatformId" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="CollarId" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="ArgosDeployment_CollarFile" Member="CollarFiles" ThisKey="DeploymentId" OtherKey="ArgosDeploymentId" Type="CollarFile" />
      <Association Name="ArgosPlatform_ArgosDeployment" Member="ArgosPlatform" ThisKey="PlatformId" OtherKey="PlatformId" Type="ArgosPlatform" IsForeignKey="true" />
      <Association Name="Collar_ArgosDeployment" Member="Collar" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="Collar" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId26">
      <Argument Parameter="platformId" Member="PlatformId" />
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="startDate" Member="StartDate" />
      <Argument Parameter="endDate" Member="EndDate" />
      <Argument Parameter="deploymentId" Member="DeploymentId" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId27">
      <Argument Parameter="deploymentId" Member="DeploymentId" Version="Original" />
      <Argument Parameter="platformId" Member="PlatformId" />
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="startDate" Member="StartDate" />
      <Argument Parameter="endDate" Member="EndDate" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId28">
      <Argument Parameter="deploymentId" Member="DeploymentId" Version="Original" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.CollarFiles" Member="CollarFiles">
    <Type Name="CollarFile">
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UploadDate" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime2 NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ProjectId" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="UserName" AutoSync="OnInsert" Type="System.String" DbType="NVarChar(128) NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="CollarId" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Format" AutoSync="OnInsert" Type="System.Char" DbType="Char(1) NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Contents" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" IsDelayLoaded="true" />
      <Column Name="ParentFileId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Sha1Hash" AutoSync="OnInsert" Type="System.Data.Linq.Binary" DbType="VarBinary(8000)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ArgosDeploymentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CollarParameterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CollarFile_CollarFix" Member="CollarFixes" ThisKey="FileId" OtherKey="FileId" Type="CollarFix" />
      <Association Name="CollarFile_ArgosDownload" Member="ArgosDownloads" ThisKey="FileId" OtherKey="FileId" Type="ArgosDownload" />
      <Association Name="CollarFile_CollarFile" Member="SubFiles" Storage="_CollarFiles" ThisKey="FileId" OtherKey="ParentFileId" Type="CollarFile" />
      <Association Name="CollarFile_ArgosFileProcessingIssue" Member="ArgosFileProcessingIssues" ThisKey="FileId" OtherKey="FileId" Type="ArgosFileProcessingIssue" />
      <Association Name="CollarFile_ArgosFilePlatformDate" Member="ArgosFilePlatformDates" ThisKey="FileId" OtherKey="FileId" Type="ArgosFilePlatformDate" />
      <Association Name="ArgosDeployment_CollarFile" Member="ArgosDeployment" ThisKey="ArgosDeploymentId" OtherKey="DeploymentId" Type="ArgosDeployment" IsForeignKey="true" />
      <Association Name="CollarFile_CollarFile" Member="ParentFile" Storage="_CollarFile1" ThisKey="ParentFileId" OtherKey="FileId" Type="CollarFile" IsForeignKey="true" />
      <Association Name="CollarParameter_CollarFile" Member="CollarParameter" ThisKey="CollarParameterId" OtherKey="ParameterId" Type="CollarParameter" IsForeignKey="true" />
      <Association Name="LookupCollarFileFormat_CollarFile" Member="LookupCollarFileFormat" ThisKey="Format" OtherKey="Code" Type="LookupCollarFileFormat" IsForeignKey="true" />
      <Association Name="LookupFileStatus_CollarFile" Member="LookupFileStatus" ThisKey="Status" OtherKey="Code" Type="LookupFileStatus" IsForeignKey="true" />
      <Association Name="ProjectInvestigator_CollarFile" Member="ProjectInvestigator" ThisKey="Owner" OtherKey="Login" Type="ProjectInvestigator" IsForeignKey="true" />
      <Association Name="Project_CollarFile" Member="Project" ThisKey="ProjectId" OtherKey="ProjectId" Type="Project" IsForeignKey="true" />
      <Association Name="Collar_CollarFile" Member="Collar" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="Collar" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId29">
      <Argument Parameter="fileName" Member="FileName" />
      <Argument Parameter="status" Member="Status" />
      <Argument Parameter="contents" Member="Contents" />
      <Argument Parameter="projectId" Member="ProjectId" />
      <Argument Parameter="owner" Member="Owner" />
      <Argument Parameter="parentFileId" Member="ParentFileId" />
      <Argument Parameter="argosDeploymentId" Member="ArgosDeploymentId" />
      <Argument Parameter="collarParameterId" Member="CollarParameterId" />
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="fileId" Member="FileId" />
      <Argument Parameter="format" Member="Format" />
      <Argument Parameter="uploadDate" Member="UploadDate" />
      <Argument Parameter="userName" Member="UserName" />
      <Argument Parameter="sha1Hash" Member="Sha1Hash" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId30">
      <Argument Parameter="fileId" Member="FileId" Version="Original" />
      <Argument Parameter="fileName" Member="FileName" />
      <Argument Parameter="status" Member="Status" />
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="projectId" Member="ProjectId" />
      <Argument Parameter="owner" Member="Owner" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId31">
      <Argument Parameter="fileId" Member="FileId" Version="Original" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.Collars" Member="Collars">
    <Type Name="Collar">
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CollarId" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CollarModel" Type="System.String" DbType="VarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="Manager" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SerialNumber" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HasGps" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DisposalDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="Collar_CollarFix" Member="CollarFixes" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="CollarFix" />
      <Association Name="Collar_CollarDeployment" Member="CollarDeployments" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="CollarDeployment" />
      <Association Name="Collar_CollarParameter" Member="CollarParameters" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="CollarParameter" />
      <Association Name="Collar_ArgosDeployment" Member="ArgosDeployments" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="ArgosDeployment" />
      <Association Name="Collar_CollarFile" Member="CollarFiles" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="CollarFile" />
      <Association Name="Collar_ArgosFileProcessingIssue" Member="ArgosFileProcessingIssues" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="ArgosFileProcessingIssue" />
      <Association Name="Collar_CollarKey" Member="CollarKeys" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="CollarKey" />
      <Association Name="Collar_CollarSensor" Member="CollarSensors" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="CollarSensor" />
      <Association Name="LookupCollarManufacturer_Collar" Member="LookupCollarManufacturer" ThisKey="CollarManufacturer" OtherKey="CollarManufacturer" Type="LookupCollarManufacturer" IsForeignKey="true" />
      <Association Name="LookupCollarModel_Collar" Member="LookupCollarModel" ThisKey="CollarManufacturer,CollarModel" OtherKey="CollarManufacturer,CollarModel" Type="LookupCollarModel" IsForeignKey="true" />
      <Association Name="ProjectInvestigator_Collar" Member="ProjectInvestigator" ThisKey="Manager" OtherKey="Login" Type="ProjectInvestigator" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId32">
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="collarModel" Member="CollarModel" />
      <Argument Parameter="manager" Member="Manager" />
      <Argument Parameter="owner" Member="Owner" />
      <Argument Parameter="serialNumber" Member="SerialNumber" />
      <Argument Parameter="frequency" Member="Frequency" />
      <Argument Parameter="hasGps" Member="HasGps" />
      <Argument Parameter="notes" Member="Notes" />
      <Argument Parameter="disposalDate" Member="DisposalDate" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId33">
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" Version="Original" />
      <Argument Parameter="collarId" Member="CollarId" Version="Original" />
      <Argument Parameter="collarModel" Member="CollarModel" />
      <Argument Parameter="manager" Member="Manager" />
      <Argument Parameter="owner" Member="Owner" />
      <Argument Parameter="serialNumber" Member="SerialNumber" />
      <Argument Parameter="frequency" Member="Frequency" />
      <Argument Parameter="hasGps" Member="HasGps" />
      <Argument Parameter="notes" Member="Notes" />
      <Argument Parameter="disposalDate" Member="DisposalDate" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId34">
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" Version="Original" />
      <Argument Parameter="collarId" Member="CollarId" Version="Original" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.ProjectInvestigatorAssistants" Member="ProjectInvestigatorAssistants">
    <Type Name="ProjectInvestigatorAssistant">
      <Column Name="ProjectInvestigator" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Assistant" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ProjectInvestigator_ProjectInvestigatorAssistant" Member="ProjectInvestigator1" ThisKey="ProjectInvestigator" OtherKey="Login" Type="ProjectInvestigator" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId35">
      <Argument Parameter="projectInvestigator" Member="ProjectInvestigator" />
      <Argument Parameter="assistant" Member="Assistant" />
    </InsertFunction>
    <DeleteFunction FunctionId="FunctionId36">
      <Argument Parameter="projectInvestigator" Member="ProjectInvestigator" Version="Original" />
      <Argument Parameter="assistant" Member="Assistant" Version="Original" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.ArgosFileProcessingIssues" Member="ArgosFileProcessingIssues">
    <Type Name="ArgosFileProcessingIssue">
      <Column Name="IssueId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Issue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PlatformId" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="CollarId" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="FirstTransmission" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="LastTransmission" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="CollarFile_ArgosFileProcessingIssue" Member="CollarFile" ThisKey="FileId" OtherKey="FileId" Type="CollarFile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Collar_ArgosFileProcessingIssue" Member="Collar" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="Collar" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="ArgosPlatform_ArgosFileProcessingIssue" Member="ArgosPlatform" ThisKey="PlatformId" OtherKey="PlatformId" Type="ArgosPlatform" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId37">
      <Argument Parameter="fileId" Member="FileId" />
      <Argument Parameter="issue" Member="Issue" />
      <Argument Parameter="platformId" Member="PlatformId" />
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="firstTransmission" Member="FirstTransmission" />
      <Argument Parameter="lastTransmission" Member="LastTransmission" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.ArgosFilePlatformDates" Member="ArgosFilePlatformDates">
    <Type Name="ArgosFilePlatformDate">
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlatformId" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ProgramId" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="FirstTransmission" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="LastTransmission" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="CollarFile_ArgosFilePlatformDate" Member="CollarFile" ThisKey="FileId" OtherKey="FileId" Type="CollarFile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="ArgosPlatform_ArgosFilePlatformDate" Member="ArgosPlatform" ThisKey="PlatformId" OtherKey="PlatformId" Type="ArgosPlatform" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CollarKeys" Member="CollarKeys">
    <Type Name="CollarKey">
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CollarId" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CollarKey" Member="Key" Type="System.String" DbType="VarChar(512)" CanBeNull="false" />
      <Association Name="Collar_CollarKey" Member="Collar" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="Collar" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId38">
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="collarKey" Member="Key" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId39">
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="collarKey" Member="Key" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId40">
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.CollarSensors" Member="CollarSensors">
    <Type Name="CollarSensor">
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CollarId" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SensorCode" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Collar_CollarSensor" Member="Collar" ThisKey="CollarManufacturer,CollarId" OtherKey="CollarManufacturer,CollarId" Type="Collar" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="LookupCollarSensor_CollarSensor" Member="LookupCollarSensor" ThisKey="CollarManufacturer,SensorCode" OtherKey="CollarManufacturer,Code" Type="LookupCollarSensor" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId41">
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="sensorCode" Member="SensorCode" />
      <Argument Parameter="isActive" Member="IsActive" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId42">
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="sensorCode" Member="SensorCode" />
      <Argument Parameter="isActive" Member="IsActive" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId43">
      <Argument Parameter="collarManufacturer" Member="CollarManufacturer" />
      <Argument Parameter="collarId" Member="CollarId" />
      <Argument Parameter="sensorCode" Member="SensorCode" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.LookupCollarSensors" Member="LookupCollarSensors">
    <Type Name="LookupCollarSensor">
      <Column Name="CollarManufacturer" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="LookupCollarSensor_CollarSensor" Member="CollarSensors" ThisKey="CollarManufacturer,Code" OtherKey="CollarManufacturer,SensorCode" Type="CollarSensor" />
      <Association Name="LookupCollarManufacturer_LookupCollarSensor" Member="LookupCollarManufacturer" ThisKey="CollarManufacturer" OtherKey="CollarManufacturer" Type="LookupCollarManufacturer" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Id="FunctionId3" Name="dbo.Animal_Delete" Method="Animal_Delete">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="AnimalId" Parameter="animalId" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId34" Name="dbo.Collar_Delete" Method="Collar_Delete">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Settings_Update" Method="Settings_Update">
    <Parameter Name="Key" Parameter="key" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Location_UpdateStatus" Method="Location_UpdateStatus">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="AnimalId" Parameter="animalId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="FixDate" Parameter="fixDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Status" Parameter="status" Type="System.Char" DbType="Char(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId6" Name="dbo.Project_Delete" Method="Project_Delete">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId4" Name="dbo.Project_Insert" Method="Project_Insert">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ProjectName" Parameter="projectName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ProjectInvestigator" Parameter="projectInvestigator" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="UnitCode" Parameter="unitCode" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(4000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId5" Name="dbo.Project_Update" Method="Project_Update">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ProjectName" Parameter="projectName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="UnitCode" Parameter="unitCode" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ProjectInvestigator" Parameter="projectInvestigator" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(4000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CollarFixes_UpdateUnhideFix" Method="CollarFixes_UpdateUnhideFix">
    <Parameter Name="FixId" Parameter="fixId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId9" Name="dbo.ProjectInvestigator_Update" Method="ProjectInvestigator_Update">
    <Parameter Name="Login" Parameter="login" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId8" Name="dbo.ProjectEditor_Delete" Method="ProjectEditor_Delete">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Editor" Parameter="editor" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId7" Name="dbo.ProjectEditor_Insert" Method="ProjectEditor_Insert">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Editor" Parameter="editor" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId1" Name="dbo.Animal_Insert" Method="Animal_Insert">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="AnimalId" Parameter="animalId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Species" Parameter="species" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="NVarChar(7)" />
    <Parameter Name="MortalityDate" Parameter="mortalityDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="GroupName" Parameter="groupName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(4000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId2" Name="dbo.Animal_Update" Method="Animal_Update">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="AnimalId" Parameter="animalId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Species" Parameter="species" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="NVarChar(7)" />
    <Parameter Name="MortalityDate" Parameter="mortalityDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="GroupName" Parameter="groupName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(4000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId15" Name="dbo.CollarParameterFile_Delete" Method="CollarParameterFile_Delete">
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId12" Name="dbo.CollarDeployment_Delete" Method="CollarDeployment_Delete">
    <Parameter Name="DeploymentId" Parameter="deploymentId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId16" Name="dbo.ArgosDownloads_Insert" Method="ArgosDownloads_Insert">
    <Parameter Name="ProgramId" Parameter="programId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="PlatformId" Parameter="platformId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Days" Parameter="days" Type="System.Int32" DbType="Int" />
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorMessage" Parameter="errorMessage" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId19" Name="dbo.ArgosPlatform_Delete" Method="ArgosPlatform_Delete">
    <Parameter Name="PlatformId" Parameter="platformId" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId21" Name="dbo.ArgosProgram_Update" Method="ArgosProgram_Update">
    <Parameter Name="OldProgramId" Parameter="oldProgramId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="NewProgramId" Parameter="newProgramId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ProgramName" Parameter="programName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Manager" Parameter="manager" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Active" Parameter="active" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId17" Name="dbo.ArgosPlatform_Insert" Method="ArgosPlatform_Insert">
    <Parameter Name="PlatformId" Parameter="platformId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ProgramId" Parameter="programId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="DisposalDate" Parameter="disposalDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Active" Parameter="active" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId18" Name="dbo.ArgosPlatform_Update" Method="ArgosPlatform_Update">
    <Parameter Name="OldPlatformId" Parameter="oldPlatformId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="NewPlatformId" Parameter="newPlatformId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ProgramId" Parameter="programId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="DisposalDate" Parameter="disposalDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Active" Parameter="active" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId22" Name="dbo.ArgosProgram_Delete" Method="ArgosProgram_Delete">
    <Parameter Name="ProgramId" Parameter="programId" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId20" Name="dbo.ArgosProgram_Insert" Method="ArgosProgram_Insert">
    <Parameter Name="ProgramId" Parameter="programId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ProgramName" Parameter="programName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Manager" Parameter="manager" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Active" Parameter="active" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId31" Name="dbo.CollarFile_Delete" Method="CollarFile_Delete">
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId10" Name="dbo.CollarDeployment_Insert" Method="CollarDeployment_Insert">
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="AnimalId" Parameter="animalId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="DeploymentDate" Parameter="deploymentDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="RetrievalDate" Parameter="retrievalDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="DeploymentId" Parameter="deploymentId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId13" Name="dbo.CollarParameterFile_Insert" Method="CollarParameterFile_Insert">
    <Parameter Name="Owner" Parameter="owner" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="FileName" Parameter="fileName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Format" Parameter="format" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Contents" Parameter="contents" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Parameter Name="Status" Parameter="status" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="UploadDate" Parameter="uploadDate" Type="System.DateTime" DbType="DateTime2" Direction="InOut" />
    <Parameter Name="UploadUser" Parameter="uploadUser" Type="System.String" DbType="NVarChar(128)" Direction="InOut" />
    <Parameter Name="Sha1Hash" Parameter="sha1Hash" Type="System.Data.Linq.Binary" DbType="VarBinary(8000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId24" Name="dbo.CollarParameter_Update" Method="CollarParameter_Update">
    <Parameter Name="ParameterId" Parameter="parameterId" Type="System.Int32" DbType="Int" />
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Gen3Period" Parameter="gen3Period" Type="System.Int32" DbType="Int" />
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime2" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId23" Name="dbo.CollarParameter_Insert" Method="CollarParameter_Insert">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Gen3Period" Parameter="gen3Period" Type="System.Int32" DbType="Int" />
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="ParameterId" Parameter="parameterId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId25" Name="dbo.CollarParameter_Delete" Method="CollarParameter_Delete">
    <Parameter Name="ParameterId" Parameter="parameterId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId28" Name="dbo.ArgosDeployment_Delete" Method="ArgosDeployment_Delete">
    <Parameter Name="DeploymentId" Parameter="deploymentId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId27" Name="dbo.ArgosDeployment_Update" Method="ArgosDeployment_Update">
    <Parameter Name="DeploymentId" Parameter="deploymentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PlatformId" Parameter="platformId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime2" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId26" Name="dbo.ArgosDeployment_Insert" Method="ArgosDeployment_Insert">
    <Parameter Name="PlatformId" Parameter="platformId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="DeploymentId" Parameter="deploymentId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId29" Name="dbo.CollarFile_Insert" Method="CollarFile_Insert">
    <Parameter Name="FileName" Parameter="fileName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Status" Parameter="status" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Contents" Parameter="contents" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Owner" Parameter="owner" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ParentFileId" Parameter="parentFileId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ArgosDeploymentId" Parameter="argosDeploymentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="CollarParameterId" Parameter="collarParameterId" Type="System.Int32" DbType="Int" />
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Format" Parameter="format" Type="System.Char" DbType="Char(1)" Direction="InOut" />
    <Parameter Name="UploadDate" Parameter="uploadDate" Type="System.DateTime" DbType="DateTime2" Direction="InOut" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(128)" Direction="InOut" />
    <Parameter Name="Sha1Hash" Parameter="sha1Hash" Type="System.Data.Linq.Binary" DbType="VarBinary(8000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId30" Name="dbo.CollarFile_Update" Method="CollarFile_Update">
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Parameter Name="FileName" Parameter="fileName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Status" Parameter="status" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Owner" Parameter="owner" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId32" Name="dbo.Collar_Insert" Method="Collar_Insert">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarModel" Parameter="collarModel" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Manager" Parameter="manager" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Owner" Parameter="owner" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="SerialNumber" Parameter="serialNumber" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Frequency" Parameter="frequency" Type="System.Double" DbType="Float" />
    <Parameter Name="HasGps" Parameter="hasGps" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DisposalDate" Parameter="disposalDate" Type="System.DateTime" DbType="DateTime2" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId33" Name="dbo.Collar_Update" Method="Collar_Update">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarModel" Parameter="collarModel" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Manager" Parameter="manager" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Owner" Parameter="owner" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="SerialNumber" Parameter="serialNumber" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Frequency" Parameter="frequency" Type="System.Double" DbType="Float" />
    <Parameter Name="HasGps" Parameter="hasGps" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DisposalDate" Parameter="disposalDate" Type="System.DateTime" DbType="DateTime2" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId35" Name="dbo.ProjectInvestigatorAssistant_Insert" Method="ProjectInvestigatorAssistant_Insert">
    <Parameter Name="ProjectInvestigator" Parameter="projectInvestigator" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Assistant" Parameter="assistant" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId36" Name="dbo.ProjectInvestigatorAssistant_Delete" Method="ProjectInvestigatorAssistant_Delete">
    <Parameter Name="ProjectInvestigator" Parameter="projectInvestigator" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Assistant" Parameter="assistant" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId14" Name="dbo.CollarParameterFile_Update" Method="CollarParameterFile_Update">
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Owner" Parameter="owner" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="FileName" Parameter="fileName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Format" Parameter="format" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Status" Parameter="status" Type="System.Char" DbType="Char(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId11" Name="dbo.CollarDeployment_Update" Method="CollarDeployment_Update">
    <Parameter Name="DeploymentId" Parameter="deploymentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProjectId" Parameter="projectId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="AnimalId" Parameter="animalId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="DeploymentDate" Parameter="deploymentDate" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="RetrievalDate" Parameter="retrievalDate" Type="System.DateTime" DbType="DateTime2" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId37" Name="dbo.ArgosFileProcessingIssues_Insert" Method="ArgosFileProcessingIssues_Insert">
    <Parameter Name="FileId" Parameter="fileId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Issue" Parameter="issue" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="PlatformId" Parameter="platformId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="FirstTransmission" Parameter="firstTransmission" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="LastTransmission" Parameter="lastTransmission" Type="System.DateTime" DbType="DateTime2" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId40" Name="dbo.CollarKey_Delete" Method="CollarKey_Delete">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId38" Name="dbo.CollarKey_Insert" Method="CollarKey_Insert">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarKey" Parameter="collarKey" Type="System.String" DbType="NVarChar(512)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId39" Name="dbo.CollarKey_Update" Method="CollarKey_Update">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarKey" Parameter="collarKey" Type="System.String" DbType="NVarChar(512)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId43" Name="dbo.CollarSensor_Delete" Method="CollarSensor_Delete">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="SensorCode" Parameter="sensorCode" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId41" Name="dbo.CollarSensor_Insert" Method="CollarSensor_Insert">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="SensorCode" Parameter="sensorCode" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId42" Name="dbo.CollarSensor_Update" Method="CollarSensor_Update">
    <Parameter Name="CollarManufacturer" Parameter="collarManufacturer" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CollarId" Parameter="collarId" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="SensorCode" Parameter="sensorCode" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
</Database>